"""initial migration

Revision ID: 59997f9e96dd
Revises: 
Create Date: 2022-12-20 18:30:01.656814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59997f9e96dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_study', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('school_study')

    # ### end Alembic commands ###
